function createHours(weekdayFrom, weekdayTo, saturdayFrom = "10:00", saturdayTo = "15:00") {
  return {
    mon: [{ from: weekdayFrom, to: weekdayTo }],
    tue: [{ from: weekdayFrom, to: weekdayTo }],
    wed: [{ from: weekdayFrom, to: weekdayTo }],
    thu: [{ from: weekdayFrom, to: weekdayTo }],
    fri: [{ from: weekdayFrom, to: weekdayTo }],
    sat: saturdayFrom && saturdayTo ? [{ from: saturdayFrom, to: saturdayTo }] : [],
    sun: [],
  };
}

export const demoUsers = [
  {
    id: 1,
    email: "user@test.pl",
    password: "123456",
    role: "USER",
    fullName: "Anna Kowalska",
    phone: "600 111 222",
    city: "Warszawa",
  },
  {
    id: 2,
    email: "owner@test.pl",
    password: "123456",
    role: "OWNER",
    fullName: "Katarzyna Nowak",
    phone: "600 222 333",
    city: "Warszawa",
    managedSalonIds: [101, 102],
  },
  {
    id: 3,
    email: "admin@test.pl",
    password: "123456",
    role: "ADMIN",
    fullName: "Michal Zielinski",
    phone: "600 333 444",
    city: "Krakow",
  },
  {
    id: 4,
    email: "klientka.wroclaw@test.pl",
    password: "123456",
    role: "USER",
    fullName: "Monika Dabrowska",
    phone: "600 444 555",
    city: "Wroclaw",
  },
  {
    id: 5,
    email: "klientka.krakow@test.pl",
    password: "123456",
    role: "USER",
    fullName: "Patrycja Lewandowska",
    phone: "600 555 666",
    city: "Krakow",
  },
];

export const demoSalons = [
  {
    id: 101,
    ownerId: 2,
    name: "Aurora Beauty Lounge",
    city: "Warszawa",
    address: "ul. Mokotowska 18, 00-561 Warszawa",
    description:
      "Nowoczesny salon beauty specjalizujacy sie w manicure premium, stylizacji brwi i zabiegach bankietowych.",
    image: "/demo/aurora-main.svg",
    imageUrl: "/demo/aurora-main.svg",
    coverImage: "/demo/aurora-cover.svg",
    rating: 4.9,
    phone: "+48 501 220 330",
    instagram: "@aurora.beauty.lounge",
    openingHours: "Pn-Pt 09:00-20:00, Sb 10:00-15:00",
    hours: createHours("09:00", "20:00"),
    images: [
      { id: 1001, url: "/demo/aurora-main.svg" },
      { id: 1002, url: "/demo/aurora-cover.svg" },
      { id: 1003, url: "/demo/aurora-gallery.svg" },
    ],
    services: [
      {
        id: 201,
        name: "Manicure hybrydowy",
        category: "Paznokcie",
        duration: 75,
        price: 139,
        description: "Opracowanie skorek, kolor hybrydowy i pielegnacja dloni.",
      },
      {
        id: 202,
        name: "Laminacja brwi z farbka",
        category: "Brwi",
        duration: 60,
        price: 129,
        description: "Modelowanie, utrwalenie wloskow i dopasowana koloryzacja.",
      },
      {
        id: 203,
        name: "Makijaz okolicznosciowy",
        category: "Makijaz",
        duration: 90,
        price: 219,
        description: "Makijaz dzienny lub wieczorowy dopasowany do urody i stylizacji.",
      },
      {
        id: 204,
        name: "Henna pudrowa + geometria",
        category: "Brwi",
        duration: 45,
        price: 99,
        description: "Precyzyjny rysunek brwi i dlugotrwaly efekt podkreslenia.",
      },
    ],
  },
  {
    id: 102,
    ownerId: 2,
    name: "Luna Skin Studio",
    city: "Wroclaw",
    address: "ul. Swidnicka 41, 50-028 Wroclaw",
    description:
      "Kameralne studio pielegnacji twarzy i ciala z naciskiem na zabiegi glow i rytualy relaksacyjne.",
    image: "/demo/luna-main.svg",
    imageUrl: "/demo/luna-main.svg",
    coverImage: "/demo/luna-cover.svg",
    rating: 4.8,
    phone: "+48 502 440 550",
    instagram: "@lunaskinstudio",
    openingHours: "Pn-Pt 10:00-19:00, Sb 09:00-14:00",
    hours: createHours("10:00", "19:00", "09:00", "14:00"),
    images: [
      { id: 1004, url: "/demo/luna-main.svg" },
      { id: 1005, url: "/demo/luna-cover.svg" },
      { id: 1006, url: "/demo/luna-gallery.svg" },
    ],
    services: [
      {
        id: 205,
        name: "Oczyszczanie wodorowe",
        category: "Twarz",
        duration: 75,
        price: 189,
        description: "Doglebne oczyszczenie, peeling i nawilzenie skory twarzy.",
      },
      {
        id: 206,
        name: "Rytual glow z masazem",
        category: "Twarz",
        duration: 90,
        price: 249,
        description: "Masaz liftingujacy i odzywcza pielegnacja przywracajaca blask.",
      },
      {
        id: 207,
        name: "Depilacja lydek",
        category: "Cialo",
        duration: 35,
        price: 79,
        description: "Szybki zabieg woskiem dla gladkiej skory na dluzej.",
      },
      {
        id: 208,
        name: "Peeling ciala i maska odzywcza",
        category: "Cialo",
        duration: 60,
        price: 169,
        description: "Relaksacyjny zabieg wygladzajacy i uelastyczniajacy skore.",
      },
    ],
  },
  {
    id: 103,
    ownerId: 3,
    name: "Velvet Hair & Beauty",
    city: "Krakow",
    address: "ul. Karmelicka 22, 31-128 Krakow",
    description:
      "Salon laczacy fryzjerstwo, koloryzacje i szybkie uslugi beauty przed spotkaniem lub sesja.",
    image: "/demo/velvet-main.svg",
    imageUrl: "/demo/velvet-main.svg",
    coverImage: "/demo/velvet-cover.svg",
    rating: 4.7,
    phone: "+48 503 660 770",
    instagram: "@velvethairbeauty",
    openingHours: "Pn-Pt 08:00-18:00, Sb 09:00-14:00",
    hours: createHours("08:00", "18:00", "09:00", "14:00"),
    images: [
      { id: 1007, url: "/demo/velvet-main.svg" },
      { id: 1008, url: "/demo/velvet-cover.svg" },
      { id: 1009, url: "/demo/velvet-gallery.svg" },
    ],
    services: [
      {
        id: 209,
        name: "Strzyzenie damskie + modelowanie",
        category: "Wlosy",
        duration: 75,
        price: 159,
        description: "Strzyzenie, modelowanie i konsultacja pielegnacyjna.",
      },
      {
        id: 210,
        name: "Koloryzacja jednolita",
        category: "Wlosy",
        duration: 150,
        price: 329,
        description: "Profesjonalna koloryzacja z dopasowana pielegnacja po zabiegu.",
      },
      {
        id: 211,
        name: "Modelowanie okazjonalne",
        category: "Wlosy",
        duration: 45,
        price: 89,
        description: "Szybkie wygladzenie lub fale przed wyjsciem.",
      },
      {
        id: 212,
        name: "Regeneracja botaniczna",
        category: "Pielegnacja",
        duration: 60,
        price: 149,
        description: "Kuracja odbudowujaca dla suchych i matowych wlosow.",
      },
    ],
  },
];

export const demoReviews = [
  {
    id: 301,
    rating: 5,
    name: "Anna K.",
    city: "Warszawa",
    text: "Bardzo wygodna rezerwacja i swietny kontakt z salonem. Manicure wykonany perfekcyjnie.",
    salonId: 101,
  },
  {
    id: 302,
    rating: 5,
    name: "Martyna S.",
    city: "Wroclaw",
    text: "Rytual glow w Luna Skin Studio to idealna opcja przed waznym wydarzeniem. Skora wygladala swietnie.",
    salonId: 102,
  },
  {
    id: 303,
    rating: 4,
    name: "Paulina R.",
    city: "Krakow",
    text: "Szybko znalazlam wolny termin na modelowanie. Caly proces w aplikacji byl intuicyjny.",
    salonId: 103,
  },
  {
    id: 304,
    rating: 5,
    name: "Joanna M.",
    city: "Warszawa",
    text: "Laminacja brwi wyszla naturalnie i bardzo estetycznie. Na pewno wroce na kolejne wizyty.",
    salonId: 101,
  },
];

function createRelativeDate(dayOffset, time) {
  const base = new Date();
  base.setHours(0, 0, 0, 0);
  base.setDate(base.getDate() + dayOffset);
  const [hours, minutes] = time.split(":").map(Number);
  base.setHours(hours, minutes, 0, 0);
  return base.toISOString();
}

export const demoBookings = [
  {
    id: 401,
    userId: 1,
    salonId: 101,
    serviceId: 201,
    clientName: "Anna Kowalska",
    clientPhone: "600 111 222",
    dateTime: createRelativeDate(1, "10:00"),
  },
  {
    id: 402,
    userId: 1,
    salonId: 102,
    serviceId: 206,
    clientName: "Anna Kowalska",
    clientPhone: "600 111 222",
    dateTime: createRelativeDate(4, "12:30"),
  },
  {
    id: 403,
    userId: 4,
    salonId: 101,
    serviceId: 202,
    clientName: "Monika Dabrowska",
    clientPhone: "600 444 555",
    dateTime: createRelativeDate(2, "14:00"),
  },
  {
    id: 404,
    userId: 5,
    salonId: 102,
    serviceId: 205,
    clientName: "Patrycja Lewandowska",
    clientPhone: "600 555 666",
    dateTime: createRelativeDate(3, "11:00"),
  },
  {
    id: 405,
    userId: 4,
    salonId: 103,
    serviceId: 210,
    clientName: "Monika Dabrowska",
    clientPhone: "600 444 555",
    dateTime: createRelativeDate(6, "09:30"),
  },
  {
    id: 406,
    userId: 1,
    salonId: 103,
    serviceId: 211,
    clientName: "Anna Kowalska",
    clientPhone: "600 111 222",
    dateTime: createRelativeDate(-5, "16:00"),
  },
  {
    id: 407,
    userId: 5,
    salonId: 101,
    serviceId: 204,
    clientName: "Patrycja Lewandowska",
    clientPhone: "600 555 666",
    dateTime: createRelativeDate(-18, "13:30"),
  },
  {
    id: 408,
    userId: 4,
    salonId: 102,
    serviceId: 208,
    clientName: "Monika Dabrowska",
    clientPhone: "600 444 555",
    dateTime: createRelativeDate(-32, "15:00"),
  },
];
